before_script:
  - apt-get update -qq
  - export SCALE_SYS=Linux64-gnu-ompi

stages:
  - build
  - test
  - doc


# BUILD

normal-rm:
  stage: build
  script:
    - apt-get install -y -qq libopenmpi-dev gfortran libnetcdf-dev
    - cd scale-rm/src
    - make -j 4
    - make -j 4 SCALE_USE_SINGLEFP=T
#    - make -j 4 SCALE_QUICKDEBUT=T
    - cd ../util/sno
    - make -j 4
  only:
    - /^feature.*$/

openmp-rm:
  stage: build
  script:
    - apt-get install -y -qq libopenmpi-dev gfortran libnetcdf-dev
    - cd scale-rm/src
    - make -j 4 SCALE_ENABLE_OPENMP=T
  only:
    - /^feature.*$/

normal-gm:
  stage: build
  script:
    - apt-get install -y -qq libopenmpi-dev gfortran libnetcdf-dev libnetcdff-dev
    - cd scale-gm/src
    - make -j 4
    - make -j 4 SCALE_USE_SINGLEFP=T
  only:
    - /^feature.*$/

openmp-gm:
  stage: build
  script:
    - apt-get install -y -qq libopenmpi-dev gfortran libnetcdf-dev libnetcdff-dev
    - cd scale-gm/src
    - make -j 4 SCALE_ENABLE_OPENMP=T
  only:
    - /^feature.*$/

#debug-gm:
#  stage: build
#  script:
#    - apt-get install -y -qq libopenmpi-dev gfortran libnetcdf-dev libnetcdff-dev
#    - cd scale-gm/src
#    - make -j 4 SCALE_QUICKDEBUT=T
#    - make -j 4 SCALE_DEBUT=T
#  only:
#    - /^feature.*$/


# TEST

lib-unit:
  stage: test
  script:
    - apt-get install -y -qq libopenmpi-dev gfortran libnetcdf-dev
    - cd scalelib/test/unit
    - make makedir
    - make makelib
    - make makebin
    - mpirun --allow-run-as-root -n 4 ./unit run.conf
  only:
    - /^feature.*$/


# DOC

ug-en:
  stage: doc
  script:
    - apt-get install -y -qq texlive-latex-base texlive-lang-japanese texlive-latex-recommended texlive-latex-extra
    - cd doc/users-guide/en
    - make
  artifacts:
    paths:
      - doc/users-guide/en/scale_users_guide_En.pdf
    expire_in: 1 mos
  only:
    - /^feature.*$/

ug-jp:
  stage: doc
  script:
    - apt-get install -y -qq texlive-latex-base texlive-lang-japanese texlive-latex-recommended texlive-latex-extra
    - cd doc/users-guide/jp
    - make
  artifacts:
    paths:
      - doc/users-guide/jp/scale_users_guide.pdf
    expire_in: 1 mos
  only:
    - /^feature.*$/

description:
  stage: doc
  script:
    - apt-get install -y -qq texlive-latex-base texlive-lang-japanese texlive-science
    - cd doc/descriptions
    - make
  artifacts:
    paths:
      - doc/descriptions/scale_rm_description.pdf
    expire_in: 1 mos
  only:
    - /^feature.*$/


reference:
  stage: doc
  script:
    - apt-get install -y -qq doxygen graphviz
    - apt-get install -y -qq texlive-latex-base texlive-lang-japanese texlive-fonts-extra
    - cd doc/reference
    - make
  artifacts:
    paths:
      - doc/reference/latex/refman.pdf
      - doc/reference/html/
    expire_in: 1 mos
  when: manual
